### PR TITLE
Adding sequence to itself to account for circular sequences

### LINKED ISSUE #9: Composite Part Algorithm needs to consider Circles
Per discussion in #8:

> (1) The detection of parts has to work on a a circular string. If we are looking for "AAAA", we'd have to detect that on "GGAAAAGG" and "AAGGGGAA". This is because plasmids are physically circles.

This should be easy to do, will put in PR soon.

### PR DESCRIPTION
**Pull request by vsoch**
This will close #9 - it's a fairly simple modification to allow for the possibility of a circular sequence, or a part being present in the circular version of the sequence. It's probably easiest to provide an example:

Let's say that we are searching for "AAAA" (a part) in our composite part. If the composite part looks like this:

```
AAGGGGAA
```
We don't find it. But if we repeat the thing you're searching in (the composite part) twice

```
AAGGGGAA -> AAGGGGAA + AAGGGGAA = AAGGGGAAAAGGGGAA
```

Then we would easily find "AAAA"

```
AAGGGGAAAAGGGGAA
```

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
One point I'm worried about - if the sequence isn't actually circular we could get false positives. One idea is to add a boolean for the user to indicate if it's a circular part, and only add it to itself if it is.

**Comment by Koeng101** [comment]
> One point I'm worried about - if the sequence isn't actually circular we could get false positives. One idea is to add a boolean for the user to indicate if it's a circular part, and only add it to itself if it is.

This is actually the purpose of composite_type ;) Though vast majority of parts (99.99%) will be ciruclar, there are a few linear plasmids.

**Comment by vsoch** [comment]
Would the boolean work then, with default set to True? That would mean if you have a non-circular part, you'd have to specify `circular=False`.

**Comment by vsoch** [comment]
okay circular boolean added, if this looks good I can merge and then go through release cycles to update the current client.

**Comment by Koeng101** [comment]
> Would the boolean work then, with default set to True? That would mean if you have a non-circular part, you'd have to specify `circular=False`.

I mean, it could work, thought it seemed like a better idea to just do it off of composite_type. So far, all our composites will be circular, and I'm doubting we'll get any linear ones soon.

**Comment by vsoch** [comment]
So "circular" is a composite_type? or "circular_plasmid" ? Just to confirm - you are saying to remove the circular boolean, and have a check for the composite_type being circular? Wouldn't it be an issue if there is a different composite_type (that is still circular) or if the user didn't provide composite_type at all (and it's likely circular but we don't check for it?) I definitely don't have your expertise, but this feels like something that would be best fit for a boolean, unless we require the user to provide a composite type, and we have a complete breakdown of exactly what types are circular.

**Comment by Koeng101** [comment]
Hmmm I guess it depends

What I was thinking of is having "base_part_plasmid" and "composite_part_plasmid" for composites, both of which can signify different things, and for circular to be assumed on those, with specific "linear_plasmid" used otherwise. That's mainly because you'll nearly never see a linear part, and that linear part will never split a part between both ends because the end sequences need to be specific sequences to enable replication. Linear plasmids are also only really used for specific applications, like doing a directed evolution experiment.

I guess it all just depends, though to be safe, we can just wait until we get a linear composite to figure out this problem (I don't really see us getting any within the next year or so).

Both booleans and composite types work I think

**Comment by vsoch** [comment]
okay - in that case, let's stick with the boolean - there is more uncertainty around the composite_types, and (worst case) we have a default argument (circular) that should be True 99% of the time, and is properly set. If a linear plasmid comes into play, great, we have a way to handle it! If not, no harm done, the default is set to be circular and the user won't make a mistake without knowing it.

**Pull request merged**
